### ISSUE TITLE
forwarding to sipUri with host of dns name does not work

### ISSUE THREAD

**Issue by davehorton** [jambonz/sbc-outbound#1]
the dial target
```
target: {
  type: 'sip'
  sipUri: 'sip:1617333456@sip.trunk1.com'
}
```
fails because currently if the host part of the sip uri is not a dot decimal address it is assumed to be a registered user.  When the lookup fails, the call is rejected with a 404

What should happen is that if the lookup fails, and the host name is not in the database for an account or service provider, we actually try to route the call to that dns name (ie DNS SRV lookup).

**Comment by davehorton** [comment]
I think this might be fixed.  @xquanluu when you get a chance (not urgent) can you test, and if working close this issue?

**Comment by xquanluu** [comment]
Hi @davehorton  tested and it's working.
