### ISSUE TITLE
Secure create-call between accounts. 

### ISSUE THREAD

**Issue by mercuryyy** [jambonz/sbc-outbound#142]
Something i'v noticed is that 

Account - A
Account -B

Number - 561-555-5555 [Assigned only to Acc (A)] 
Number - 954-111-1111 [Assigned only to Acc (B)] 

Carrier - XYZ

Carrier is assigned to all accounts. 

It is possible with Account (A) account_sid and api_token to create a call to 954-111-1111
I would place a hard check if the phone number exists in the account before even sending the call to get routed.

**Comment by davehorton** [comment]
when you say "create a call" what exactly is this scenario?  Using a POST createCall api to create an outbound call?

**Comment by mercuryyy** [comment]
Yes, Using a POST to API with [Account - A] credentials to call "954-111-1111"

**Comment by davehorton** [comment]
Closing this issue as there is nothing wrong with that.  It's perfectly fine to try dial **any** PSTN number from account A.  The fact that it happens to be a number associated with any jambonz system, or this jambonz system with a different account is irrelevant.  jambonz does not validate the numbers you try to call to from the sip trunks you have set up.
