### ISSUE TITLE
Additional routing logic

### ISSUE THREAD

**Issue by davehorton** [jambonz/sbc-outbound#85]
Currently, the routing logic goes like this:
1. If the dial target specifies a trunk, we use that
2. If the calling party number is a phone number in the caller's account or SP, we use the associated carrier
3. If the account or SP has LCR configured, we use that
4. Otherwise we randomly select an outbound carrier

I would like to insert a new rule before that last one:
- If the call came in from a carrier, and that carrier has active outbound sip gateways, then use that carrier

In other words, say I have 3 carriers A, B, and C.  I have not set up LCR but a call comes in on A and I dial out.  If no target is specified and the calling number is not in our database (and, as mentioned, there are no LCR), then **if** carrier A has active outbound gateways then use carrier A.  In other words, default to sending calls out on the same carrier they came in on.

Note this will probably mean passing a custom header `X-Inbound-Carrier` or something from the INVITE from the FS so that sbc-outbound knows if there as an associated inbound call that came from a carrier

**Comment by xquanluu** [comment]
Start working on this.

**Comment by xquanluu** [comment]
sbc-inbound have to add X-Inbound-Carrier and send it to FS
FS will forward this header to sbc-outbound

**Comment by xquanluu** [comment]
sbc-inbound already add X-Voip-Carrier-Sid

**Comment by xquanluu** [comment]
PR merged, closing this issue
